name: authentication_repository
description: Repository which manages user authentication using Firebase Authentication.

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0