name: troop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  analytics: 
    path: package/analytics/
  authentication_repository:
    path: package/authentication_repository/
  platform_helper:
    path: package/platform_helper/
  troop_ui:
    path: package/troop_ui/
  routemaster: ^1.0.1
  flutter_riverpod: ^1.0.4
  logging: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/