name: troop_ui
description: A Flutter package which helps detect the host platform

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  url_launcher: ^6.0.3
  platform_helper:
    path: ../platform_helper/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
